# Generated by Django 4.1 on 2022-08-12 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_alter_group_scientific_name"),
        ("animals", "0006_animal_traits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animals",
                to="groups.group",
            ),
        ),
    ]
