# Generated by Django 4.1 on 2022-08-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0003_alter_animal_group"),
        ("traits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trait",
            name="animals",
            field=models.ManyToManyField(related_name="traits", to="animals.animal"),
        ),
    ]
