# Generated by Django 4.1 on 2022-08-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traits", "0002_trait_animals"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trait",
            name="animals",
        ),
    ]
